import json
import re
from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from typing import Any


class AIProviderError(Exception):
    def __init__(
        self,
        message: str,
        *,
        status_code: int = 502,
        provider: str = "ai",
        model: str | None = None,
        response_body: str | None = None,
    ) -> None:
        super().__init__(message)
        self.message = message
        self.status_code = status_code
        self.provider = provider
        self.model = model
        self.response_body = response_body


class AIProvider(ABC):
    provider_name = "base"

    @abstractmethod
    async def repository_summary(self, context: dict[str, Any]) -> dict[str, Any]:
        raise NotImplementedError

    @abstractmethod
    async def chat(self, context: dict[str, Any], question: str) -> str:
        raise NotImplementedError

    async def stream_chat(self, context: dict[str, Any], question: str) -> AsyncIterator[str]:
        yield await self.chat(context, question)

    @abstractmethod
    async def commit_intelligence(self, context: dict[str, Any]) -> dict[str, Any]:
        raise NotImplementedError

    @abstractmethod
    async def readme(self, context: dict[str, Any]) -> str:
        raise NotImplementedError


def repository_summary_fallback(context: dict[str, Any]) -> dict[str, Any]:
    return {
        "overview": f"{context['full_name']} is a {context.get('language') or 'software'} repository.",
        "architecture": "The repository structure suggests a modular application. Configure an AI provider for deeper architectural analysis.",
        "detected_stack": context.get("technologies", []),
        "probable_purpose": context.get("description") or "The repository purpose can be inferred from its files and commit history.",
        "beginner_explanation": "This project contains source files, configuration, and history that GitSense can summarize for new contributors.",
    }


def commit_intelligence_fallback(context: dict[str, Any]) -> dict[str, Any]:
    messages = [commit["message"].split("\n")[0] for commit in context.get("commits", [])[:5]]
    return {
        "commit_summaries": messages,
        "contributor_insights": ["Configure an AI provider for richer contributor analysis."],
        "weekly_progress_summary": "Recent commits are available; AI weekly synthesis is disabled until provider credentials are configured.",
    }


def readme_fallback(context: dict[str, Any]) -> str:
    return f"""# {context['full_name']}

## Overview
{context.get('description') or 'Repository overview generated by GitSense.'}

## Tech Stack
{', '.join(context.get('technologies') or ['To be detected'])}

## Installation
Clone the repository, install dependencies, and follow project-specific scripts.

## Usage
Run the application using the commands documented in the source configuration.

## Contributing
Open a focused pull request with clear context, tests where appropriate, and a concise description.
"""


def parse_json_object(content: str, *, provider: str, model: str | None = None) -> dict[str, Any]:
    try:
        parsed = json.loads(content)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", content, flags=re.DOTALL)
        if not match:
            raise AIProviderError("AI provider returned malformed JSON.", status_code=502, provider=provider, model=model, response_body=content)
        try:
            parsed = json.loads(match.group(0))
        except json.JSONDecodeError as exc:
            raise AIProviderError("AI provider returned malformed JSON.", status_code=502, provider=provider, model=model, response_body=content) from exc
    if not isinstance(parsed, dict):
        raise AIProviderError("AI provider returned an unexpected response shape.", status_code=502, provider=provider, model=model, response_body=content)
    return parsed
